//! Code generation for yogurt subgraphs.
//!
//! This crate reads `subgraph.yaml`, `schema.graphql`, and ABI JSON files
//! to generate type-safe Rust code.

mod abi;
mod error;
mod manifest;
mod schema;

pub use abi::AbiParser;
pub use error::{CodegenError, Result};
pub use manifest::{DataSource, Manifest};
pub use schema::SchemaParser;

use std::fs;
use std::path::Path;

/// Generate all Rust code for a subgraph.
pub fn generate(manifest_path: &Path, output_dir: &Path) -> Result<()> {
    // Read and parse the manifest
    let manifest_content = fs::read_to_string(manifest_path)?;
    let manifest = Manifest::parse(&manifest_content)?;

    // Ensure output directory exists
    fs::create_dir_all(output_dir)?;

    // Parse schema and generate entity types
    if let Some(schema_path) = manifest_path.parent().map(|p| p.join(&manifest.schema.file))
    {
        let schema_content = fs::read_to_string(&schema_path)?;
        let schema = SchemaParser::parse(&schema_content)?;
        let schema_code = schema.generate_rust();
        fs::write(output_dir.join("schema.rs"), schema_code)?;
    }

    // Parse ABIs and generate event/contract types
    let mut abi_modules = Vec::new();

    for data_source in &manifest.data_sources {
        for abi in &data_source.mapping.abis {
            if let Some(abi_path) = manifest_path.parent().map(|p| p.join(&abi.file)) {
                let abi_content = fs::read_to_string(&abi_path)?;
                let parsed_abi = AbiParser::parse(&abi_content)?;
                let module_name = abi.name.to_lowercase();
                let abi_code = parsed_abi.generate_rust(&abi.name);
                fs::write(output_dir.join(format!("{}.rs", module_name)), abi_code)?;
                abi_modules.push(module_name);
            }
        }
    }

    // Generate mod.rs
    let mod_code = generate_mod_rs(&abi_modules);
    fs::write(output_dir.join("mod.rs"), mod_code)?;

    Ok(())
}

fn generate_mod_rs(abi_modules: &[String]) -> String {
    let mut code = String::from(
        "//! Auto-generated by yogurt codegen — do not edit\n\n\
         mod schema;\n",
    );

    for module in abi_modules {
        code.push_str(&format!("mod {};\n", module));
    }

    code.push_str("\npub use schema::*;\n");

    for module in abi_modules {
        code.push_str(&format!("pub use {}::*;\n", module));
    }

    code
}
